export const COMMAND_AGENTS = "AI-AGENTS";
export const COMMAND_UPSCALE = "UPSCALE";
export const COMMAND_REMOVEBACKGROUND = "REMOVE-BACKGROUND";
export const COMMAND_ACCOUNT = "ACCOUNT";
export const COMMAND_SUPPORT = "SUPPORT";
export const COMMAND_INTRO = "INTRO";
export const COMMAND_CHANGE_API_KEY = "CHANGE_API_KEY";
export const COMMAND_GENERATE_IMAGE = "GENERATE-IMAGE";

export default {
    COMMAND_AGENTS,
    COMMAND_UPSCALE,
    COMMAND_REMOVEBACKGROUND,
    COMMAND_ACCOUNT,
    COMMAND_SUPPORT,
    COMMAND_INTRO,
    COMMAND_CHANGE_API_KEY,
    COMMAND_GENERATE_IMAGE
}

    